type CartProduct {
  id: String!
  code: String
  quantity: Float
  timestamp: Float
}

input CartProductPayload {
  id: String!
  code: String
  quantity: Float
  timestamp: Float
}

type Cart {
  id: String!
  timestamp: Float
  products: [CartProduct]
}

input CartPayload {
  id: String!
  timestamp: Float
  products: [CartProductPayload]
}

type Query {
  getCartById(id: ID): Cart
  getAllCarts: [Cart]!
}

type Mutation {
  addCart(id: String!, timestamp: Float!, products: [CartProductPayload]!): Cart
  addProductById(cartId: String!, productId: String!): Boolean
  editCart(cart: CartPayload): Boolean
}
